name: Tag Release

on:
  push:
    branches:
      - main  # Run this workflow when pushing to the main branch

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js (for semantic versioning)
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Get current version
        id: get_version
        run: |
          # Get the current tag (latest semantic version tag) or default to 0.0.0
          git fetch --tags
          VERSION=$(git describe --tags --abbrev=0 2>/dev/null || echo "0.0.0")
          echo "current_version=$VERSION" >> $GITHUB_ENV

      - name: Calculate new version
        id: calculate_version
        run: |
          # Define how to increment the version (major, minor, patch)
          # Example: Increment patch version for each successful main branch build
          IFS='.' read -r major minor patch <<< "$current_version"
          patch=$((patch + 1))
          new_version="$major.$minor.$patch"
          echo "new_version=$new_version" >> $GITHUB_ENV

      - name: Tag the new version
        if: steps.calculate_version.outputs.new_version != ''
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git tag -a "v$new_version" -m "Release $new_version"
          git push origin "v$new_version"

      - name: Confirm tag creation
        run: git describe --tags
