name: CI/CD Pipeline for Hello World App

on:
  push:
    branches:
      - main

jobs:
  tag-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Bump Version and Push Tag
        id: tag
        uses: anothrNick/github-tag-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          semver: true

      - name: Output new version
        run: echo "New version is ${{ steps.tag.outputs.new_tag }}"

  build-and-push:
    runs-on: ubuntu-latest
    needs: tag-version
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/hello-world:${{ steps.tag.outputs.new_tag }} .
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/hello-world:${{ steps.tag.outputs.new_tag }}
