name: Tag Release

on:
  push:
    branches:
      - main  # Adjust this branch if needed

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Get current version
        id: get_version
        run: |
          git fetch --tags
          VERSION=$(git describe --tags --abbrev=0 2>/dev/null || echo "0.0.0")
          echo "current_version=$VERSION" >> $GITHUB_ENV

      - name: Calculate new version
        id: calculate_version
        run: |
          IFS='.' read -r major minor patch <<< "$current_version"
          patch=$((patch + 1))
          new_version="$major.$minor.$patch"
          echo "new_version=$new_version" >> $GITHUB_ENV

      - name: Configure Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Tag the new version
        if: steps.calculate_version.outputs.new_version != ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git tag -a "v$new_version" -m "Release $new_version"
          git push origin "v$new_version"

      - name: Confirm tag creation
        run: git describe --tags
