name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy (e.g., dev, test, stg, prod)'
        required: true
        type: choice
        options:
          - dev
          - test
          - stg
          - prod

jobs:
  deploy:
    uses: devopscka/pub1/.github/workflows/deploy-workflow.yml@main
    with:
      deploy_target: ${{ github.event.inputs.environment }}
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      AZURE_USERNAME: ${{ secrets.AZURE_USERNAME }}
      AZURE_PASSWORD: ${{ secrets.AZURE_PASSWORD }}
