name: Environment-Specific Deployments

on:
  push:
    branches:
      - main

jobs:
  deploy_dev:
    name: Deploy to Development
    uses: organization-or-username/centralized-workflows/.github/workflows/deploy.yml@main
    with:
      environment: "dev"
      version: "v1.0.0"  # Set dynamically as needed
    secrets:
      DEPLOY_SECRET: ${{ secrets.DEV_DEPLOY_SECRET }}

  deploy_test:
    name: Deploy to Testing
    needs: deploy_dev  # Ensures this job runs only after deploy_dev succeeds
    uses: organization-or-username/centralized-workflows/.github/workflows/deploy.yml@main
    with:
      environment: "test"
      version: "v1.0.0"
    secrets:
      DEPLOY_SECRET: ${{ secrets.TEST_DEPLOY_SECRET }}

  deploy_staging:
    name: Deploy to Staging
    needs: deploy_test  # Waits for deploy_test to complete
    environment: stg  # Specifies the "stg" environment with required approvals
    uses: organization-or-username/centralized-workflows/.github/workflows/deploy.yml@main
    with:
      environment: "stg"
      version: "v1.0.0"
    secrets:
      DEPLOY_SECRET: ${{ secrets.STAGING_DEPLOY_SECRET }}

  deploy_prod:
    name: Deploy to Production
    needs: deploy_staging  # Waits for deploy_staging to complete
    environment: prod  # Specifies the "prod" environment with required approvals
    uses: organization-or-username/centralized-workflows/.github/workflows/deploy.yml@main
    with:
      environment: "prod"
      version: "v1.0.0"
    secrets:
      DEPLOY_SECRET: ${{ secrets.PROD_DEPLOY_SECRET }}
