name: Call Semantic Version Tagging

on:
  push:
    branches:
      - main
      - 'hotfix/*'

jobs:
  invoke-semantic-version:
    uses: devopscka/workflow/.github/workflows/semantic-version-tagging.yml@main
    with:
      branches:
        - main
        - 'hotfix/*'
