name: Invoke Semantic Version Tagging

on:
  push:
    branches:
      - main
      - 'hotfix/*'

jobs:
  invoke:
    uses: devopscka/workflow/.github/workflows/semantic-version-tagging.yml@main
    with:
      branch: ${{ github.ref_name }}
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

